spring:
  application:
    name : gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
          - Path=/api/users/**
          - Path=/login/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/v1/products/**

        - id: order-microservice
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/v1/orders/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/v1/payments/**


server:
  port:8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG